apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appointment-app
  template:
    metadata:
      labels:
        app: appointment-app
    spec:
      serviceAccountName: ecr-puller
      containers:
        - name: appointment-service
          image: 945839052546.dkr.ecr.us-east-1.amazonaws.com/appointment:appointmentimage
          ports:
            - containerPort: 3001
      imagePullSecrets:
        - name: ecr-pull-secret
